/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package componente;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Cristhian
 */
public class Contraseña extends javax.swing.JPanel {

    /**
     * Creates new form Contraseña
     */
    public Contraseña() {
        initComponents();
        Icono.setIcon(Cerrado);
    }
    
    private Icon Abierto=new ImageIcon(getClass().getResource("Abierto.png"));
    private Icon Cerrado=new ImageIcon(getClass().getResource("Cerrado.png"));
    private int longitudContraseña = 8; // valor predeterminado
    private String mensajeFacil = "Fácil";
    private String mensajeMedio = "Media";
    private String mensajeSeguro = "Segura";
    private Color colorFacil = Color.red;
    private Color colorMedio = Color.yellow;
    private Color colorSeguro = Color.green;

    public Icon getAbierto()
    {
        return Abierto;
    }

    public Icon getCerrado()
    {
        return Cerrado;
    }

    public Color getColorFacil()
    {
        return colorFacil;
    }

    public Color getColorMedio()
    {
        return colorMedio;
    }

    public Color getColorSeguro()
    {
        return colorSeguro;
    }
    
    
    public String getMensajeFacil()
    {
        return mensajeFacil;
    }
    
    public void setMensajeFacil(String mensajeFacil)
    {
        this.mensajeFacil = mensajeFacil;
    }

    public String getMensajeMedio()
    {
        return mensajeMedio;
    }
    
    public void setMensajeMedio(String mensajeMedio)
    {
        this.mensajeMedio = mensajeMedio;
    }

    public String getMensajeSeguro(){
        return mensajeSeguro;
    }

    public void setMensajeSeguro(String mensajeSeguro){
        this.mensajeSeguro = mensajeSeguro;
    }

    public int getLongitudContraseña() 
    {
        return longitudContraseña;
    }

    public void setLongitudContraseña(int longitudContraseña)
    {
        this.longitudContraseña = longitudContraseña;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contraseña = new javax.swing.JPasswordField();
        SeguridadTxt = new javax.swing.JLabel();
        Icono = new javax.swing.JLabel();

        Contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ContraseñaKeyReleased(evt);
            }
        });

        SeguridadTxt.setFont(new java.awt.Font("HarmonyOS Sans SC Medium", 0, 12)); // NOI18N

        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componente/Cerrado.png"))); // NOI18N
        Icono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IconoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                IconoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeguridadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Icono)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Icono, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(Contraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeguridadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContraseñaKeyReleased
        // TODO add your handling code here:
        ActualizarSeguridad();
    }//GEN-LAST:event_ContraseñaKeyReleased

    private void IconoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoMousePressed
        // TODO add your handling code here:
        Contraseña.setEchoChar((char)0);
        Icono.setIcon(Abierto);
    }//GEN-LAST:event_IconoMousePressed

    private void IconoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoMouseReleased
        // TODO add your handling code here:
        Contraseña.setEchoChar('*');
        Icono.setIcon(Cerrado);
    }//GEN-LAST:event_IconoMouseReleased

    private void ActualizarSeguridad()
    {
        char [] contraseña=Contraseña.getPassword();
        int nivelS=Seguridad(contraseña);
        if(nivelS<=2)
        {
            SeguridadTxt.setForeground(Color.red);
            SeguridadTxt.setText(mensajeFacil);
        }
        else if(nivelS<=4)
        {
            SeguridadTxt.setForeground(Color.yellow);
            SeguridadTxt.setText(mensajeMedio);
        }
        else
        {
            SeguridadTxt.setForeground(Color.green);
            SeguridadTxt.setText(mensajeSeguro);
        }
        
        
    }
    
    private int Seguridad(char [] password)
    {
        int cont=0;
        String cadena = new String(password);
        boolean minuscula=cadena.matches(".*[a-z].*");
        boolean mayuscula=cadena.matches(".*[A-Z].*");
        boolean numero=cadena.matches(".*[0-9].*");
        boolean caracter=cadena.matches(".*[!@#$%^&*(),.?\":{}|<>].*");
        boolean tamaño=cadena.length()>=longitudContraseña;
        if(minuscula)
        {
            cont++;
        }
        if(mayuscula)
        {
            cont++;
        }
        if(numero)
        {
            cont++;
        }
        if(caracter)
        {
            cont++;
        }
        if(tamaño)
        {
            cont++;
        }
        
        return cont;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JLabel Icono;
    private javax.swing.JLabel SeguridadTxt;
    // End of variables declaration//GEN-END:variables
}
